version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - bridge
    ports:
    - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

