CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lists (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    list_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, list_name)
);

CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    items_id INTEGER REFERENCES lists(id) ON DELETE CASCADE,
    data VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
